title: "HubGaming"
description: "AI-powered strategies, esports analytics & Web3 gaming."
url: "https://hubgaming.io"    # nếu đang dùng Netlify subdomain, update sau
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false

author: "HubGaming Team"

# SEO
plugins:
  - jekyll-sitemap

# Google Analytics
google_analytics: "G-JY5VL0G11T"
